---
- name: Show issue file
  hosts: all
  tasks:
    - name: Show Issue
      ansible.builtin.raw: cat /etc/issue
      register: command_output

    - name: Print to console
      debug: msg = "{{command_output.stdout}}"