---
- name: Update and upgrade apt packages
  hosts: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        name: '*'
        state: latest
        update_cache: yes