---
- name: Update and upgrade dnf packages
  hosts: fedora
  become: yes
  become_method: sudo
  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'dnf'
      ansible.builtin.dnf:
        name: '*'
        state: latest