---
- name: Update and upgrade all packages
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Update packages with dnf
      when: ansible_pkg_mgr == 'dnf'
      ansible.builtin.dnf:
        name: '*'
        state: latest
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        name: '*'
        state: latest
        update_cache: yes